'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Lerryn.Presentation.eShopCONNECT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;NewDataSet&gt;
        '''  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        '''    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        '''      &lt;xs:complexType&gt;
        '''        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        '''          &lt;xs:element name=&quot;ModifiedSystemTables&quot;&gt;
        '''            &lt;xs:complexType&gt;
        '''              &lt;xs:sequence&gt;
        '''                &lt;xs:element name=&quot;Table [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DataDictionaryDataset() As String
            Get
                Return ResourceManager.GetString("DataDictionaryDataset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*=======================================================================*/
        '''/* Connected Business SDK                                                  */
        '''/* Copyright Â© 2004-2008 Interprise Solutions LLC      */
        '''/* All rights reserved.                                                  */
        '''/*                                                                       */
        '''/* Interprise Plugin Factory - Generated Code                            */
        '''/*                                              [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DataDictionaryScript() As String
            Get
                Return ResourceManager.GetString("DataDictionaryScript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InvImpDone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvImpDone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InvImpSKUChanged() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvImpSKUChanged", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InvImpSKUExists() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvImpSKUExists", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lerrynlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lerrynlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SelectAll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectAll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SelectNone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SelectNone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UpLevel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UpLevel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        '''&lt;UserRoleDataset&gt;
        '''  &lt;SystemUserRoleMenuForm&gt;
        '''    &lt;Counter&gt;2462&lt;/Counter&gt;
        '''    &lt;RoleCode&gt;Administrator&lt;/RoleCode&gt;
        '''    &lt;MenuGroupCode&gt;Inventory&lt;/MenuGroupCode&gt;
        '''    &lt;FormMenuCode&gt;5082255E-816A-4C18-B1C7-44F1110090AE&lt;/FormMenuCode&gt;
        '''    &lt;TreeParentID&gt;01&lt;/TreeParentID&gt;
        '''    &lt;TreeChildID&gt;01&lt;/TreeChildID&gt;
        '''    &lt;FormAssemblyName&gt;Entity&lt;/FormAssemblyName&gt;
        '''    &lt;FormClassType&gt;Entity&lt;/FormClassType&gt;
        '''    &lt;FormModuleClassType&gt;Entity&lt;/FormModuleClassType&gt;
        '''    &lt;IsEnabled&gt;true&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UserRoleScript() As String
            Get
                Return ResourceManager.GetString("UserRoleScript", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
